name: CI
on:
    push:
        branches:
            - master
    pull_request:

jobs:
    build-for-automerge:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false
            - name: Use Node.js 22
              uses: actions/setup-node@v3
              with:
                  node-version: 22
            - run: |
                  npm install
                  npm run build

    automerge:
        needs: build-for-automerge
        runs-on: ubuntu-latest

        permissions:
            pull-requests: write
            contents: write

        steps:
            - uses: fastify/github-action-merge-dependabot@v3
